-- 기존 COMPICK Oracle DB에 Google 로그인 기능을 추가할 때 1회 실행한다.

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SQLBLANKLINES ON;

ALTER SESSION SET CURRENT_SCHEMA = COMPICK;

CREATE TABLE SOCIAL_ACCOUNT (
    social_account_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    member_id          NUMBER(19)    NOT NULL,
    provider           VARCHAR2(20)  NOT NULL,
    provider_user_id   VARCHAR2(255) NOT NULL,
    provider_email     VARCHAR2(100) NOT NULL,
    setup_completed    CHAR(1) DEFAULT 'N' NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_social_account PRIMARY KEY (social_account_id),
    CONSTRAINT fk_social_account_member
        FOREIGN KEY (member_id) REFERENCES MEMBER (member_id),
    CONSTRAINT uk_social_provider_user
        UNIQUE (provider, provider_user_id),
    CONSTRAINT ck_social_provider
        CHECK (provider IN ('GOOGLE')),
    CONSTRAINT ck_social_setup_completed
        CHECK (setup_completed IN ('Y', 'N'))
);

COMMENT ON TABLE SOCIAL_ACCOUNT IS '회원 소셜 로그인 연결 정보';
COMMENT ON COLUMN SOCIAL_ACCOUNT.provider IS '소셜 로그인 제공자';
COMMENT ON COLUMN SOCIAL_ACCOUNT.provider_user_id IS '제공자 회원 식별자';
COMMENT ON COLUMN SOCIAL_ACCOUNT.setup_completed IS '소셜 가입 후 비밀번호 설정 완료 여부';

COMMIT;
EXIT;
