-- 기존 주문 프로젝트의 APP_MEMBER(VARCHAR2) 참조를
-- member 프로젝트의 MEMBER(NUMBER(19,0)) 참조로 변경한다.
-- ORDERS 데이터가 비어 있거나 MEMBER_ID가 숫자로 변환 가능한 경우에만 실행한다.

ALTER TABLE ORDERS DROP CONSTRAINT FK160Y9JI4UPY5XGM2YPAWNCI4T;
ALTER TABLE ORDERS MODIFY MEMBER_ID NUMBER(19,0);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_MEMBER
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

-- 과거 주문 샘플 엔티티에서 사용하던 컬럼 제거
ALTER TABLE ORDERS DROP COLUMN ORDER_DATE;
ALTER TABLE ORDERS DROP COLUMN RECEIVER_ADDRESS;
ALTER TABLE ORDERS DROP COLUMN RECEIVER_NAME;
ALTER TABLE ORDERS DROP COLUMN TOTAL_PRICE;

COMMIT;
