-- ============================================================
-- COMPICK Oracle Database Schema
-- 기준 패키지: com.boot.compick
-- 기준 DB: Oracle 12c 이상 (IDENTITY 사용)
-- ============================================================

-- ============================================================
-- 1. 회원
-- ============================================================

CREATE TABLE MEMBER (
    member_id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    login_id        VARCHAR2(50)  NOT NULL,
    password_hash   VARCHAR2(255) NOT NULL,
    member_name     VARCHAR2(50)  NOT NULL,
    email           VARCHAR2(100) NOT NULL,
    nickname        VARCHAR2(20)  NOT NULL,
    phone           VARCHAR2(20)  NOT NULL,
    member_role     VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
    member_status   VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_member PRIMARY KEY (member_id),
    CONSTRAINT uk_member_login_id UNIQUE (login_id),
    CONSTRAINT uk_member_email UNIQUE (email),
    CONSTRAINT ck_member_role
        CHECK (member_role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_member_status
        CHECK (member_status IN ('ACTIVE', 'INACTIVE', 'WITHDRAWN'))
);

-- ============================================================
-- 2. 배송지
-- MEMBER 1 : N ADDRESS
-- ============================================================

CREATE TABLE ADDRESS (
    address_id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    member_id        NUMBER(19)    NOT NULL,
    address_name     VARCHAR2(50)  NOT NULL,
    recipient_name   VARCHAR2(50)  NOT NULL,
    recipient_phone  VARCHAR2(20)  NOT NULL,
    zip_code         VARCHAR2(10)  NOT NULL,
    basic_address    VARCHAR2(255) NOT NULL,
    detail_address   VARCHAR2(255),
    is_default       CHAR(1)       DEFAULT 'N' NOT NULL,
    created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_address PRIMARY KEY (address_id),
    CONSTRAINT fk_address_member
        FOREIGN KEY (member_id) REFERENCES MEMBER (member_id),
    CONSTRAINT ck_address_is_default
        CHECK (is_default IN ('Y', 'N'))
);

-- ============================================================
-- 2-1. 소셜 계정
-- MEMBER 1 : N SOCIAL_ACCOUNT
-- ============================================================

CREATE TABLE SOCIAL_ACCOUNT (
    social_account_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    member_id          NUMBER(19)    NOT NULL,
    provider           VARCHAR2(20)  NOT NULL,
    provider_user_id   VARCHAR2(255) NOT NULL,
    provider_email     VARCHAR2(100) NOT NULL,
    setup_completed    CHAR(1) DEFAULT 'N' NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_social_account PRIMARY KEY (social_account_id),
    CONSTRAINT fk_social_account_member
        FOREIGN KEY (member_id) REFERENCES MEMBER (member_id),
    CONSTRAINT uk_social_provider_user
        UNIQUE (provider, provider_user_id),
    CONSTRAINT ck_social_provider
        CHECK (provider IN ('GOOGLE')),
    CONSTRAINT ck_social_setup_completed
        CHECK (setup_completed IN ('Y', 'N'))
);

-- ============================================================
-- 2-2. 이메일 인증
-- ============================================================

CREATE TABLE EMAIL_VERIFICATION (
    verification_id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    email                    VARCHAR2(100) NOT NULL,
    purpose                  VARCHAR2(30)  NOT NULL,
    verification_code_hash  VARCHAR2(255) NOT NULL,
    expires_at               TIMESTAMP     NOT NULL,
    attempt_count            NUMBER(5)     DEFAULT 0 NOT NULL,
    verified_at              TIMESTAMP,
    used_at                  TIMESTAMP,
    created_at               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_email_verification PRIMARY KEY (verification_id),
    CONSTRAINT ck_email_verification_purpose
        CHECK (purpose IN ('SIGN_UP', 'FIND_ID', 'PASSWORD_RESET')),
    CONSTRAINT ck_email_verification_attempt
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_email_verification_lookup
    ON EMAIL_VERIFICATION (email, purpose, created_at);

-- ============================================================
-- 3. 카테고리
-- CATEGORY 1 : N PRODUCT
-- ============================================================

CREATE TABLE CATEGORY (
    category_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    category_name  VARCHAR2(30) NOT NULL,

    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT uk_category_name UNIQUE (category_name),
    CONSTRAINT ck_category_name CHECK (
        category_name IN (
            'CPU',
            'CPU_COOLER',
            'MAINBOARD',
            'GPU',
            'STORAGE',
            'RAM',
            'CASE',
            'POWER_SUPPLY'
        )
    )
);

-- ============================================================
-- 4. 상품
-- 호환성 검사에 자주 사용하는 값은 별도 컬럼으로 저장하고,
-- 나머지 상세 사양은 spec_json에 JSON 문자열로 저장한다.
-- ============================================================

CREATE TABLE PRODUCT (
    product_id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    category_id            NUMBER(19)     NOT NULL,
    product_name           VARCHAR2(255)  NOT NULL,
    brand                  VARCHAR2(100)  NOT NULL,
    model_name             VARCHAR2(150)  NOT NULL,
    price                  NUMBER(12)     NOT NULL,
    rating_count           NUMBER(10)     DEFAULT 0 NOT NULL,
    stock_quantity         NUMBER(10)     DEFAULT 0 NOT NULL,
    product_description    CLOB,
    image_url              VARCHAR2(1000),
    sales_status           VARCHAR2(20)   DEFAULT 'ON_SALE' NOT NULL,
    socket_type            VARCHAR2(50),
    memory_type            VARCHAR2(50),
    form_factor            VARCHAR2(50),
    power_consumption      NUMBER(8),
    recommended_power      NUMBER(8),
    gpu_length_mm          NUMBER(8),
    max_gpu_length_mm      NUMBER(8),
    power_capacity_watt    NUMBER(8),
    spec_json              CLOB,
    created_at             TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_product PRIMARY KEY (product_id),
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES CATEGORY (category_id),
    CONSTRAINT ck_product_price
        CHECK (price >= 0),
    CONSTRAINT ck_product_rating_count
        CHECK (rating_count >= 0),
    CONSTRAINT ck_product_stock
        CHECK (stock_quantity >= 0),
    CONSTRAINT ck_product_sales_status
        CHECK (sales_status IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN', 'DISCONTINUED')),
    CONSTRAINT ck_product_power_consumption
        CHECK (power_consumption IS NULL OR power_consumption >= 0),
    CONSTRAINT ck_product_recommended_power
        CHECK (recommended_power IS NULL OR recommended_power >= 0),
    CONSTRAINT ck_product_gpu_length
        CHECK (gpu_length_mm IS NULL OR gpu_length_mm >= 0),
    CONSTRAINT ck_product_max_gpu_length
        CHECK (max_gpu_length_mm IS NULL OR max_gpu_length_mm >= 0),
    CONSTRAINT ck_product_power_capacity
        CHECK (power_capacity_watt IS NULL OR power_capacity_watt >= 0),
    CONSTRAINT ck_product_spec_json
        CHECK (spec_json IS JSON)
);

-- ============================================================
-- 5. 견적
-- MEMBER 1 : N QUOTE
-- QUOTE N : M PRODUCT 관계를 QUOTE_ITEM이 해소한다.
-- 총가격과 총전력은 PRODUCT 값과 QUOTE_ITEM 수량으로 계산한다.
-- ============================================================

CREATE TABLE QUOTE (
    quote_id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    member_id             NUMBER(19)    NOT NULL,
    quote_name            VARCHAR2(150) NOT NULL,
    quote_type            VARCHAR2(20)  NOT NULL,
    assembly_type         VARCHAR2(20)  DEFAULT 'SELF' NOT NULL,
    purpose_tag           VARCHAR2(20),
    summary_description   VARCHAR2(200),
    image_url             VARCHAR2(1000),
    created_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_quote PRIMARY KEY (quote_id),
    CONSTRAINT fk_quote_member
        FOREIGN KEY (member_id) REFERENCES MEMBER (member_id),
    CONSTRAINT ck_quote_type
        CHECK (quote_type IN ('USER', 'PRESET', 'AI')),
    CONSTRAINT ck_quote_assembly_type
        CHECK (assembly_type IN ('SELF', 'ASSEMBLED')),
    CONSTRAINT ck_quote_purpose_tag
        CHECK (purpose_tag IS NULL OR purpose_tag IN ('OFFICE', 'GAMING', 'VIDEO_EDIT', 'BEGINNER'))
);

CREATE TABLE QUOTE_ITEM (
    quote_item_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    quote_id       NUMBER(19) NOT NULL,
    product_id     NUMBER(19) NOT NULL,
    quantity       NUMBER(10) DEFAULT 1 NOT NULL,

    CONSTRAINT pk_quote_item PRIMARY KEY (quote_item_id),
    CONSTRAINT fk_quote_item_quote
        FOREIGN KEY (quote_id) REFERENCES QUOTE (quote_id) ON DELETE CASCADE,
    CONSTRAINT fk_quote_item_product
        FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id),
    CONSTRAINT uk_quote_item_product
        UNIQUE (quote_id, product_id),
    CONSTRAINT ck_quote_item_quantity
        CHECK (quantity > 0)
);

-- ============================================================
-- 6. AI 추천
-- 성공하여 QUOTE가 생성된 AI 추천만 저장한다.
-- 일반/프리셋 견적에는 AI 추천 정보가 없을 수 있으므로
-- QUOTE 1 : 0..1 AI_RECOMMENDATION 관계이다.
-- ============================================================

CREATE TABLE AI_RECOMMENDATION (
    ai_recommendation_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    quote_id              NUMBER(19) NOT NULL,
    user_requirements     CLOB       NOT NULL,
    ai_answer_json        CLOB       NOT NULL,

    CONSTRAINT pk_ai_recommendation
        PRIMARY KEY (ai_recommendation_id),
    CONSTRAINT fk_ai_recommendation_quote
        FOREIGN KEY (quote_id) REFERENCES QUOTE (quote_id) ON DELETE CASCADE,
    CONSTRAINT uk_ai_recommendation_quote
        UNIQUE (quote_id),
    CONSTRAINT ck_ai_answer_json
        CHECK (ai_answer_json IS JSON)
);

-- ============================================================
-- 7. 장바구니
-- MEMBER 1 : 1 CART
-- 일반 상품과 견적 상품의 구조가 달라 항목 테이블을 분리한다.
-- ============================================================

CREATE TABLE CART (
    cart_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    member_id    NUMBER(19) NOT NULL,
    created_at   TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_cart PRIMARY KEY (cart_id),
    CONSTRAINT fk_cart_member
        FOREIGN KEY (member_id) REFERENCES MEMBER (member_id),
    CONSTRAINT uk_cart_member UNIQUE (member_id)
);

CREATE TABLE CART_PRODUCT_ITEM (
    cart_product_item_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    cart_id               NUMBER(19) NOT NULL,
    product_id            NUMBER(19) NOT NULL,
    quantity              NUMBER(10) DEFAULT 1 NOT NULL,
    is_selected           CHAR(1)    DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_cart_product_item
        PRIMARY KEY (cart_product_item_id),
    CONSTRAINT fk_cart_product_item_cart
        FOREIGN KEY (cart_id) REFERENCES CART (cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_product_item_product
        FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id),
    CONSTRAINT uk_cart_product_item
        UNIQUE (cart_id, product_id),
    CONSTRAINT ck_cart_product_item_quantity
        CHECK (quantity > 0),
    CONSTRAINT ck_cart_product_item_selected
        CHECK (is_selected IN ('Y', 'N'))
);

CREATE TABLE CART_QUOTE_ITEM (
    cart_quote_item_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    cart_id             NUMBER(19) NOT NULL,
    quote_id            NUMBER(19) NOT NULL,
    quantity            NUMBER(10) DEFAULT 1 NOT NULL,
    is_selected         CHAR(1)    DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_cart_quote_item
        PRIMARY KEY (cart_quote_item_id),
    CONSTRAINT fk_cart_quote_item_cart
        FOREIGN KEY (cart_id) REFERENCES CART (cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_quote_item_quote
        FOREIGN KEY (quote_id) REFERENCES QUOTE (quote_id) ON DELETE CASCADE,
    CONSTRAINT uk_cart_quote_item
        UNIQUE (cart_id, quote_id),
    CONSTRAINT ck_cart_quote_item_quantity
        CHECK (quantity > 0),
    CONSTRAINT ck_cart_quote_item_selected
        CHECK (is_selected IN ('Y', 'N'))
);

-- ============================================================
-- 8. 주문
-- ORDERS는 주문서 전체와 주문 시점의 배송지 스냅샷을 저장한다.
-- ORDER_GROUP은 견적/일반 상품 묶음을 저장한다.
-- ORDER_ITEM은 실제 구매 상품과 주문 당시 가격을 저장한다.
-- ============================================================

CREATE TABLE ORDERS (
    order_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    member_id         NUMBER(19)     NOT NULL,
    order_number      VARCHAR2(50)   NOT NULL,
    order_status      VARCHAR2(30)   DEFAULT 'PAYMENT_PENDING' NOT NULL,
    product_amount    NUMBER(12)     NOT NULL,
    shipping_fee      NUMBER(12)     DEFAULT 0 NOT NULL,
    final_amount      NUMBER(12)     NOT NULL,
    recipient_name    VARCHAR2(50)   NOT NULL,
    recipient_phone   VARCHAR2(20)   NOT NULL,
    zip_code          VARCHAR2(10)   NOT NULL,
    basic_address     VARCHAR2(255)  NOT NULL,
    detail_address    VARCHAR2(255),
    delivery_request  VARCHAR2(500),
    return_requested_at TIMESTAMP,
    stock_deducted_at TIMESTAMP,
    stock_restored_at TIMESTAMP,
    ordered_at        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id) REFERENCES MEMBER (member_id),
    CONSTRAINT uk_orders_order_number
        UNIQUE (order_number),
    CONSTRAINT ck_orders_status CHECK (
        order_status IN (
            'PAYMENT_PENDING',
            'PAID',
            'PREPARING',
            'SHIPPING',
            'DELIVERED',
            'CANCELLED'
        )
    ),
    CONSTRAINT ck_orders_product_amount
        CHECK (product_amount >= 0),
    CONSTRAINT ck_orders_shipping_fee
        CHECK (shipping_fee >= 0),
    CONSTRAINT ck_orders_final_amount
        CHECK (final_amount >= 0)
);

CREATE TABLE ORDER_GROUP (
    order_group_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    order_id         NUMBER(19)    NOT NULL,
    source_quote_id  NUMBER(19),
    group_type       VARCHAR2(20)  NOT NULL,
    group_name       VARCHAR2(150) NOT NULL,
    group_quantity   NUMBER(10)    DEFAULT 1 NOT NULL,
    assembly_type    VARCHAR2(20)  DEFAULT 'SELF' NOT NULL,

    CONSTRAINT pk_order_group PRIMARY KEY (order_group_id),
    CONSTRAINT fk_order_group_order
        FOREIGN KEY (order_id) REFERENCES ORDERS (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_group_source_quote
        FOREIGN KEY (source_quote_id)
        REFERENCES QUOTE (quote_id) ON DELETE SET NULL,
    CONSTRAINT ck_order_group_type
        CHECK (group_type IN ('QUOTE', 'PRODUCT')),
    CONSTRAINT ck_order_group_quantity
        CHECK (group_quantity > 0),
    CONSTRAINT ck_order_group_assembly_type
        CHECK (assembly_type IN ('SELF', 'ASSEMBLED')),
    -- 원본 견적은 이후 삭제될 수 있으므로 QUOTE 그룹도 NULL을 허용한다.
    -- 단, 일반 상품 그룹에는 원본 견적이 연결되면 안 된다.
    CONSTRAINT ck_order_group_source CHECK (
        group_type = 'QUOTE'
        OR
        (group_type = 'PRODUCT' AND source_quote_id IS NULL)
    )
);

CREATE TABLE ORDER_ITEM (
    order_item_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    order_id          NUMBER(19)    NOT NULL,
    order_group_id    NUMBER(19)    NOT NULL,
    product_id        NUMBER(19)    NOT NULL,
    product_name      VARCHAR2(255) NOT NULL,
    order_price       NUMBER(12)    NOT NULL,
    quantity          NUMBER(10)    NOT NULL,
    line_amount       NUMBER(12)    NOT NULL,

    CONSTRAINT pk_order_item PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id) REFERENCES ORDERS (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_group
        FOREIGN KEY (order_group_id)
        REFERENCES ORDER_GROUP (order_group_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id),
    CONSTRAINT ck_order_item_price
        CHECK (order_price >= 0),
    CONSTRAINT ck_order_item_quantity
        CHECK (quantity > 0),
    CONSTRAINT ck_order_item_line_amount
        CHECK (line_amount >= 0)
);

-- ============================================================
-- 9. 결제
-- 한 주문은 결제 정보를 최대 한 건 가진다.
-- ORDERS 1 : 0..1 PAYMENT
-- ============================================================

CREATE TABLE PAYMENT (
    payment_id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    order_id                NUMBER(19)    NOT NULL,
    payment_method          VARCHAR2(30)  NOT NULL,
    payment_amount          NUMBER(12)    NOT NULL,
    payment_status          VARCHAR2(20)  DEFAULT 'READY' NOT NULL,
    external_transaction_id VARCHAR2(100),
    approval_number         VARCHAR2(100),
    requested_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    approved_at             TIMESTAMP,
    cancelled_at            TIMESTAMP,

    CONSTRAINT pk_payment PRIMARY KEY (payment_id),
    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id) REFERENCES ORDERS (order_id),
    CONSTRAINT uk_payment_order
        UNIQUE (order_id),
    CONSTRAINT uk_payment_transaction
        UNIQUE (external_transaction_id),
    CONSTRAINT ck_payment_amount
        CHECK (payment_amount >= 0),
    CONSTRAINT ck_payment_status
        CHECK (payment_status IN ('READY', 'APPROVED', 'FAILED', 'CANCELLED'))
);

-- ============================================================
-- 10. 외래키 조회용 인덱스
-- Oracle은 FK 인덱스를 자동 생성하지 않으므로 별도로 생성한다.
-- UNIQUE 제약조건으로 이미 인덱스가 만들어지는 컬럼 조합은 제외했다.
-- ============================================================

CREATE INDEX idx_address_member
    ON ADDRESS (member_id);

CREATE INDEX idx_product_category
    ON PRODUCT (category_id);

CREATE INDEX idx_quote_member
    ON QUOTE (member_id);

CREATE INDEX idx_quote_item_product
    ON QUOTE_ITEM (product_id);

CREATE INDEX idx_cart_product_item_product
    ON CART_PRODUCT_ITEM (product_id);

CREATE INDEX idx_cart_quote_item_quote
    ON CART_QUOTE_ITEM (quote_id);

CREATE INDEX idx_orders_member
    ON ORDERS (member_id);

CREATE INDEX idx_order_group_order
    ON ORDER_GROUP (order_id);

CREATE INDEX idx_order_group_source_quote
    ON ORDER_GROUP (source_quote_id);

CREATE INDEX idx_order_item_order
    ON ORDER_ITEM (order_id);

CREATE INDEX idx_order_item_group
    ON ORDER_ITEM (order_group_id);

CREATE INDEX idx_order_item_product
    ON ORDER_ITEM (product_id);

-- ============================================================
-- 11. 기본 카테고리 데이터
-- ============================================================

INSERT INTO CATEGORY (category_name) VALUES ('CPU');
INSERT INTO CATEGORY (category_name) VALUES ('CPU_COOLER');
INSERT INTO CATEGORY (category_name) VALUES ('MAINBOARD');
INSERT INTO CATEGORY (category_name) VALUES ('GPU');
INSERT INTO CATEGORY (category_name) VALUES ('STORAGE');
INSERT INTO CATEGORY (category_name) VALUES ('RAM');
INSERT INTO CATEGORY (category_name) VALUES ('CASE');
INSERT INTO CATEGORY (category_name) VALUES ('POWER_SUPPLY');

COMMIT;

-- ============================================================
-- 참고
-- 1. updated_at은 INSERT 때만 기본값이 입력된다.
--    수정 시각 자동 갱신은 JPA Auditing으로 처리한다.
-- 2. 회원과 상품은 과거 주문 보존을 위해 물리 삭제보다
--    member_status, sales_status를 이용한 논리 삭제를 권장한다.
-- 3. 같은 회원에게 기본 배송지는 하나만 허용해야 한다.
--    Oracle의 일반 UNIQUE 제약조건만으로 조건부 유일성을 표현하기
--    어려우므로 Service에서 변경 시 기존 기본 배송지를 해제한다.
-- 4. ORDER_ITEM의 order_id와 ORDER_GROUP의 order_id가 일치하는지는
--    주문 생성 Service에서 반드시 검증한다.
-- ============================================================
