-- 회원가입 이메일 인증 기능을 위한 EMAIL_VERIFICATION 테이블을 추가한다.

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SQLBLANKLINES ON;

ALTER SESSION SET CURRENT_SCHEMA = COMPICK;

CREATE TABLE EMAIL_VERIFICATION (
    verification_id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    email                    VARCHAR2(100) NOT NULL,
    purpose                  VARCHAR2(30)  NOT NULL,
    verification_code_hash  VARCHAR2(255) NOT NULL,
    expires_at               TIMESTAMP     NOT NULL,
    attempt_count            NUMBER(5)     DEFAULT 0 NOT NULL,
    verified_at              TIMESTAMP,
    used_at                  TIMESTAMP,
    created_at               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_email_verification PRIMARY KEY (verification_id),
    CONSTRAINT ck_email_verification_purpose
        CHECK (purpose IN ('SIGN_UP', 'FIND_ID', 'PASSWORD_RESET')),
    CONSTRAINT ck_email_verification_attempt
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_email_verification_lookup
    ON EMAIL_VERIFICATION (email, purpose, created_at);

COMMIT;
EXIT;
